"""create hotel url field

Revision ID: a8a06ba9c400
Revises: 
Create Date: 2024-07-09 19:19:37.945032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8a06ba9c400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_facility_association')
    op.drop_index('ix_hotels_id', table_name='hotels')
    op.drop_table('hotels')
    op.drop_index('ix_images_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_facilities_id', table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('facilities_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='facilities_pkey'),
    sa.UniqueConstraint('name', name='facilities_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_facilities_id', 'facilities', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='images_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hotels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_comments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hotels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_hotels_id', 'hotels', ['id'], unique=False)
    op.create_table('hotel_facility_association',
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name='hotel_facility_association_facility_id_fkey'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='hotel_facility_association_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('hotel_id', 'facility_id', name='hotel_facility_association_pkey')
    )
    # ### end Alembic commands ###
